# Generated by Django 4.0.4 on 2022-05-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cathegory',
            options={'verbose_name_plural': 'cathegories'},
        ),
    ]
